FROM golang:latest

WORKDIR /app

# copy Go modules and dependencies to image
COPY go.mod ./

# download Go modules and dependencies
RUN go mod download

# copy directory files i.e all files ending with .go
COPY . .

RUN go build -o ./routegen ./cmd/routegen/routegen.go

ENV PORT 8080

EXPOSE $PORT

CMD ["./routegen"]